_BASE_: "../dior_base.yaml"
MODEL:
  WEIGHTS: "log/DIOR/10-10/STEP0/model_final.pth"
  ROI_HEADS:
    NUM_CLASSES: 20
    NUM_BASE_CLASSES: 10
    NUM_NOVEL_CLASSES: 5
    LEARN_INCREMENTALLY: True
    TRAIN_ON_BASE_CLASSES: False
SOLVER:
  STEPS: (7725,)
  MAX_ITER: 9250
  IMS_PER_BATCH: 4
  LR_SCHEDULER_NAME: WarmupMultiStepLR
DISTILL:
  ENABLE: True
WG:
  ENABLE: True
  IMAGE_STORE_LOC: "log/DIOR/10-10/img_store.pth"
OUTPUT_DIR: "log/DIOR/10-5/STEP1/INC"