_BASE_: "../dior_base.yaml"
MODEL:
  WEIGHTS: "cache/R-50.pkl"
  ROI_HEADS:
    NUM_CLASSES: 20
    NUM_BASE_CLASSES: 10
    NUM_NOVEL_CLASSES: 10
    LEARN_INCREMENTALLY: True
    TRAIN_ON_BASE_CLASSES: True
SOLVER:
  STEPS: (8690, 11911)
  MAX_ITER: 12985
  LR_SCHEDULER_NAME: WarmupMultiStepLR
DISTILL:
  ENABLE: False
WG:
  ENABLE: True
  IMAGE_STORE_LOC: "log/DIOR/10-10/img_store.pth"
OUTPUT_DIR: "log/DIOR/10-10/STEP0"