_BASE_: "../dior_base.yaml"
MODEL:
  WEIGHTS: "log/DIOR/15-5/STEP0/model_final.pth"
  ROI_HEADS:
    NUM_CLASSES: 20
    NUM_BASE_CLASSES: 15
    NUM_NOVEL_CLASSES: 5
    LEARN_INCREMENTALLY: True
    TRAIN_ON_BASE_CLASSES: False
SOLVER:
  STEPS: (4414,)
  MAX_ITER: 5276
  IMS_PER_BATCH: 4
  WARMUP_ITERS: 100
  LR_SCHEDULER_NAME: WarmupMultiStepLR
DISTILL:
  ENABLE: True
WG:
  ENABLE: True
  IMAGE_STORE_LOC: "log/DIOR/15-5/15_p_5.pth"
OUTPUT_DIR: "log/DIOR/15-5/STEP1/INC"