_BASE_: "../dota_base.yaml"
MODEL:
  WEIGHTS: "cache/R-50.pkl"
  ROI_HEADS:
    NUM_CLASSES: 15
    NUM_BASE_CLASSES: 14
    NUM_NOVEL_CLASSES: 1
    LEARN_INCREMENTALLY: True
    TRAIN_ON_BASE_CLASSES: True
SOLVER:
  STEPS: (10543, 14459)
  MAX_ITER: 15764
  LR_SCHEDULER_NAME: WarmupMultiStepLR
DISTILL:
  ENABLE: False
WG:
  ENABLE: True
  IMAGE_STORE_LOC: "log/DOTA/14-1/img_store.pth"
OUTPUT_DIR: "log/DOTA/14-1/STEP0"