_BASE_: "../dota_base.yaml"
MODEL:
  WEIGHTS: "log/DOTA/14-1/STEP0/model_final.pth"
  ROI_HEADS:
    NUM_CLASSES: 15
    NUM_BASE_CLASSES: 14
    NUM_NOVEL_CLASSES: 1
    LEARN_INCREMENTALLY: True
    TRAIN_ON_BASE_CLASSES: False
SOLVER:
  STEPS: (800,)
  MAX_ITER: 1000
  IMS_PER_BATCH: 4
  WARMUP_ITERS: 100
  LR_SCHEDULER_NAME: WarmupMultiStepLR
DISTILL:
  ENABLE: True
WG:
  ENABLE: True
  IMAGE_STORE_LOC: "log/DOTA/14-1/14_p_1.pth"
OUTPUT_DIR: "log/DOTA/14-1/STEP1/INC"