_BASE_: "../dota_base.yaml"
MODEL:
  WEIGHTS: "cache/R-50.pkl"
  ROI_HEADS:
    NUM_CLASSES: 15
    NUM_BASE_CLASSES: 5
    NUM_NOVEL_CLASSES: 10
    LEARN_INCREMENTALLY: True
    TRAIN_ON_BASE_CLASSES: True
SOLVER:
  BASE_LR: 0.01
  STEPS: (6752, 9246)
  MAX_ITER: 10078
  IMS_PER_BATCH: 8
  LR_SCHEDULER_NAME: WarmupMultiStepLR
DISTILL:
  ENABLE: False
WG:
  ENABLE: False
  IMAGE_STORE_LOC: "log/DOTA/5-10/5_p_10.pth"
OUTPUT_DIR: "log/DOTA/5-10/STEP0"