_BASE_: "../dota_base.yaml"
MODEL:
  WEIGHTS: "log/DOTA/5-10/STEP1/INC/model_final.pth"
  ROI_HEADS:
    NUM_CLASSES: 15
    NUM_BASE_CLASSES: 5
    NUM_NOVEL_CLASSES: 10
    LEARN_INCREMENTALLY: False
    TRAIN_ON_BASE_CLASSES: False
SOLVER:
  IMS_PER_BATCH: 8
  MAX_ITER: 100
  EXPLICIT_LR: 0.0001
  LR_SCHEDULER_NAME: FixedLR
DISTILL:
  ENABLE: False
WG:
  ENABLE: False
  IMAGE_STORE_LOC: "log/DOTA/5-10/5_p_10.pth"
FINETUNE:
  MIN_NUM_IMG_PER_CLASS: 10
  BATCH_SIZE: 2
OUTPUT_DIR: "log/DOTA/5-10/STEP1/FT"