_BASE_: "../dota_base.yaml"
MODEL:
  WEIGHTS: "log/DOTA/5-10/STEP0/model_final.pth"
  ROI_HEADS:
    NUM_CLASSES: 15
    NUM_BASE_CLASSES: 5
    NUM_NOVEL_CLASSES: 10
    LEARN_INCREMENTALLY: True
    TRAIN_ON_BASE_CLASSES: False
SOLVER:
  STEPS: (8472,)
  MAX_ITER: 10147
  IMS_PER_BATCH: 4
  LR_SCHEDULER_NAME: WarmupMultiStepLR
DISTILL:
  ENABLE: True
WG:
  ENABLE: True
  IMAGE_STORE_LOC: "log/DOTA/5-10/img_store.pth"
OUTPUT_DIR: "log/DOTA/5-10/STEP1/INC"