_BASE_: "../dior_base.yaml"
MODEL:
  WEIGHTS: "cache/R-50.pkl"
  ROI_HEADS:
    NUM_CLASSES: 20
    NUM_BASE_CLASSES: 19
    NUM_NOVEL_CLASSES: 1
    LEARN_INCREMENTALLY: True
    TRAIN_ON_BASE_CLASSES: True
SOLVER:
  STEPS: (11020, 15115)
  MAX_ITER: 16480
  LR_SCHEDULER_NAME: WarmupMultiStepLR
DISTILL:
  ENABLE: False
WG:
  ENABLE: True
  IMAGE_STORE_LOC: "log/DIOR/19-1/img_store.pth"
OUTPUT_DIR: "log/DIOR/19-1/STEP0"