_BASE_: "../dior_base.yaml"
MODEL:
  WEIGHTS: "log/DIOR/19-1/STEP0/model_final.pth"
  ROI_HEADS:
    NUM_CLASSES: 20
    NUM_BASE_CLASSES: 19
    NUM_NOVEL_CLASSES: 1
    LEARN_INCREMENTALLY: True
    TRAIN_ON_BASE_CLASSES: False
SOLVER:
  STEPS: (1109,)
  MAX_ITER: 1310
  IMS_PER_BATCH: 4
  WARMUP_ITERS: 100
  LR_SCHEDULER_NAME: WarmupMultiStepLR
DISTILL:
  ENABLE: True
WG:
  ENABLE: True
  IMAGE_STORE_LOC: "log/DIOR/19-1/19_p_1.pth"
OUTPUT_DIR: "log/DIOR/19-1/STEP1/INC"