_BASE_: "../dior_base.yaml"
MODEL:
  WEIGHTS: "log/DIOR/5-15/STEP0/model_final.pth"
  ROI_HEADS:
    NUM_CLASSES: 20
    NUM_BASE_CLASSES: 5
    NUM_NOVEL_CLASSES: 15
    LEARN_INCREMENTALLY: True
    TRAIN_ON_BASE_CLASSES: False
SOLVER:
  STEPS: (11318,)
  MAX_ITER: 13561
  IMS_PER_BATCH: 4
  LR_SCHEDULER_NAME: WarmupMultiStepLR
DISTILL:
  ENABLE: True
WG:
  ENABLE: True
  IMAGE_STORE_LOC: "log/DIOR/5-15/img_store.pth"
OUTPUT_DIR: "log/DIOR/5-15/STEP1/INC"