_BASE_: "../dota_base.yaml"
MODEL:
  WEIGHTS: "log/DOTA/8-7/STEP0/model_final.pth"
  ROI_HEADS:
    NUM_CLASSES: 15
    NUM_BASE_CLASSES: 8
    NUM_NOVEL_CLASSES: 7
    LEARN_INCREMENTALLY: True
    TRAIN_ON_BASE_CLASSES: False
SOLVER:
  STEPS: (5532,)
  MAX_ITER: 6619
  IMS_PER_BATCH: 4
  LR_SCHEDULER_NAME: WarmupMultiStepLR
DISTILL:
  ENABLE: True
WG:
  ENABLE: True
  IMAGE_STORE_LOC: "log/DOTA/8-7/img_store.pth"
OUTPUT_DIR: "log/DOTA/8-7/STEP1/INC"